### ISSUE TITLE
spawn vehicle

### ISSUE THREAD

**Issue by TonTonSheitan** [indilo53/fivem-esx_slaughtererjob#1]
Hi indilo, I have a little worry when more than 3 people take the vehicle for delivery the 4th player make spawn a vehicle and suddenly it removes one of the other 3 truck, unable to have more than 3 truck On maps

sorry i use google translate xD 

THX.

**Comment by indilo53** [comment]
Je n'ai actuellement pas de solution pour le despawn de véhicules

**Comment by TonTonSheitan** [comment]
oui ya pas de souci, ce n'est pas un problème primaire ;)


________________________________
De : indilo53 <notifications@github.com>
Envoyé : mardi 23 mai 2017 17:23
À : indilo53/fivem-esx_slaughtererjob
Cc : TonTonSheitan; Author
Objet : Re: [indilo53/fivem-esx_slaughtererjob] spawn vehicle (#1)


Je n'ai actuellement pas de solution pour le despawn de véhicules
